Feature/e UI 3220 spinner component aa
hmcts/rpx-xui-common-lib pull request #122
Opened 2021-02-16 14:42 UTC by adnanakgun

Resolves https://tools.hmcts.net/jira/browse/EUI-3220

Created the component

Notes:
*
*
*

2021-02-16 15:10 UTC, udaydenduluri33 approved these changes
LGTMa

2021-02-16 15:21 UTC, paul-graham commented on projects/exui-common-lib/src/lib/components/loading-spinner/loading-spinner.component.scss
> +        &:nth-child(1) {
Maybe replace all of these with `@include spinnerDivs(12)`, where the mixin looks something like:
```
@mixin spinnerDivs($count) {
  @for $i from 1 through $count {
    &.nth-child(#{$i}) {
      transform: rotate(#{30 * ($i - 1)}deg);
      animation-delay: #{($i / 10) - 1.2}s;
    }
  }
}
```

2021-02-16 16:26 UTC, paulhowes-HMCTS requested changes
I think both my recommendation and Paul G's would make the code more efficient.

2021-02-16 16:26 UTC, paulhowes-HMCTS commented on projects/exui-common-lib/src/lib/components/loading-spinner/loading-spinner.component.html
> +      <div></div>
Could reduce this by replacing all the empty divs with <div *ngFor="let i of [].constructor(12)"></div>

2021-02-17 08:24 UTC, paulhowes-HMCTS approved these changes

2021-02-17 09:51 UTC, paul-graham approved these changes

2021-02-17 13:42 UTC, merged