FINAL CHANGES
hmcts/rpx-xui-common-lib pull request #177
Opened 2021-09-21 11:05 UTC by waynepHMCTS

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)

Notes:
*
*
*

2021-09-27 13:50 UTC, Daniel-Lam requested changes
@waynepHMCTS - a couple of things to look at:
* Please remove `package-lock.json`. This has been superseded by `yarn.lock`
* Please add some unit tests for the new `http-global-interceptor`

2021-09-28 08:12 UTC, kuda1992 requested changes
You need to change the package.json version name from 1.4.3-display-case-filters" to 1.4.3-not-all-exceptions" or you won't be able to create a tag.

2021-09-28 10:34 UTC, Daniel-Lam requested changes
@waynepHMCTS - still needs some unit tests for the new interceptor.

2021-09-30 10:09 UTC, Daniel-Lam requested changes
@waynepHMCTS - thanks for adding a unit test. Is it possible to extend it to cover both branches of execution? I notice in the implementation there's a check for whether it's a client-side error or a server-side error.

2021-10-01 09:59 UTC, udaydenduluri33 approved these changes

2021-10-05 11:19 UTC, kuda1992 approved these changes

2021-10-05 11:34 UTC, Daniel-Lam requested changes
@waynepHMCTS - all looks good, except for a few, minor linting issues

2021-10-05 11:34 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/services/http-global-interceptors/http-global-interceptor.spec.ts
> +          handle: () =>  throwError(mock404Error)
@waynepHMCTS - linting: extra whitespace after `=>`

2021-10-05 11:34 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/services/http-global-interceptors/http-global-interceptor.spec.ts
> +            console.log(res);
@waynepHMCTS - linting: indentation (should be 2 spaces)

2021-10-05 11:34 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/services/http-global-interceptors/http-global-interceptor.spec.ts
> +            expect(errorInterceptor.assignErrorMessage).toHaveBeenCalledWith(mock404Error);
@waynepHMCTS - linting: indentation (should be 2 spaces)

2021-10-05 11:34 UTC, Daniel-Lam commented on projects/exui-common-lib/package.json
> +  "version": "1.4.3-add-interceptor-for-global-error-handling",
@waynepHMCTS - linting: extra whitespace at line end

2021-10-05 12:25 UTC, Daniel-Lam approved these changes

2021-10-05 13:27 UTC, merged