EUI-4679 Date error formatting margin adjustment
hmcts/rpx-xui-common-lib pull request #185
Opened 2021-11-02 17:13 UTC by johnbenjamin-hmcts

JIRA https://tools.hmcts.net/jira/browse/EUI-4679

Notes: Date input and text input formatting

2021-11-02 18:12 UTC, Daniel-Lam requested changes
@johnbenjamin-hmcts - just a few minor observations.

2021-11-02 18:12 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/gov-ui/components/gov-uk-date/gov-uk-date.component.html
> +<div id="date-input-container" class="govuk-form-group" [ngClass]="{'govuk-form-group--error': errorMessage?.isInvalid}" [formGroup]="formGroup">
@johnbenjamin-hmcts - what happens if there is more than one `gov-uk-date` component on a page... maybe a problem with duplicate IDs? How about something that's a bit more dynamic, based on the `config` that is passed in? For example, you could do: `<div [id]="config.id+'-date-input-container'">` or similar. I appreciate you'll have to change the CSS selector in `gov-uk-date.component.scss`.

2021-11-02 18:12 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/gov-ui/components/gov-uk-date/gov-uk-date.component.scss
> +#date-input-container {
@johnbenjamin-hmcts - as above, you might need to change the CSS selector depending on what you do with the `date-input-container` ID above.

2021-11-02 18:12 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/gov-ui/components/gov-uk-input/gov-uk-input.component.html
> +<xuilib-gov-uk-error-message [config]="config" [errorMessage]="errorMessage" *ngIf="errorMessage"></xuilib-gov-uk-error-message>
@johnbenjamin-hmcts - probably no harm leaving the `*ngIf` here, but is there ever a scenario where `errorMessage` is provided but is falsy? In other words, would there ever be an empty error message?

2021-11-03 09:28 UTC, RiteshHMCTS approved these changes

2021-11-03 10:11 UTC, Daniel-Lam requested changes
@johnbenjamin-hmcts - just the one comment on the CSS style; everything else looks OK.

2021-11-03 10:11 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/gov-ui/components/gov-uk-date/gov-uk-date.component.scss
> +  margin-bottom: 30px !important;
@johnbenjamin-hmcts - hmm... is there another way of applying the style without using `!important`? It's usually frowned upon to use this override.

2021-11-03 12:14 UTC, Daniel-Lam approved these changes
@johnbenjamin-hmcts - nice rework, I see you wrapped the whole date component in another `<div>` with a `date-input-container` class.

2021-11-04 09:24 UTC, merged