Changes for all work filters
hmcts/rpx-xui-common-lib pull request #249
Opened 2022-03-10 14:45 UTC by connorpgpmcelroy

Resolves #https://tools.hmcts.net/jira/browse/EUI-5221. (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)

Notes:
- Emit events from find location and find person to change radio buttons on selection
- Ensure enable condition (which resets fields) is not the same as disable to allow new logic to work while not surrendering ability to disable fields
- Changing filter model slightly
- Adding new tests (mostly checking event emitters work)

2022-03-10 18:57 UTC, udaydenduluri33 approved these changes

2022-03-14 16:16 UTC, scott-turner-hmcts requested changes
could of minor things otherwise looks good

2022-03-14 16:46 UTC, connorpgpmcelroy commented on projects/exui-common-lib/src/lib/components/find-location/find-location.component.ts
> +  @Input() public disableInputField: boolean = false;
sure

2022-03-14 16:46 UTC, connorpgpmcelroy commented on projects/exui-common-lib/src/lib/components/find-location/find-location.component.ts
> +    }
agreed

2022-03-14 16:46 UTC, connorpgpmcelroy commented on projects/exui-common-lib/src/lib/components/generic-filter/generic-filter.component.ts
> +      if (typeof field.radioSelectionChange === 'string') {
agreed

2022-03-14 17:15 UTC, merged