Make required error message changes
hmcts/rpx-xui-common-lib pull request #421
Opened 2023-10-25 16:09 UTC by connorpgpmcelroy

Resolves #https://tools.hmcts.net/jira/browse/EUI-8937

Notes:
* Change error display

2023-10-26 11:57 UTC, Daniel-Lam requested changes
@connorpgpmcelroy - two minor observations; otherwise OK

2023-10-26 11:57 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/components/write-address/write-address.component.html
> +    <span class="govuk-label"><b>Provide address details</b></span>
@connorpgpmcelroy - `<b>` tag is deprecated; use `<strong>` instead (see https://www.w3schools.com/tags/tag_b.asp)

2023-10-26 11:57 UTC, Daniel-Lam commented on projects/exui-common-lib/src/lib/models/address-message.enum.ts
> +    INVALID_POSTCODE = 'Enter valid postcode',
@connorpgpmcelroy - trailing comma and new line can be removed

2023-10-26 16:00 UTC, Daniel-Lam approved these changes

2023-10-27 10:48 UTC, johnbenjamin-hmcts approved these changes

2023-10-27 10:50 UTC, merged