Bug/cot 726 final
hmcts/rpx-xui-common-lib pull request #443
Opened 2024-01-30 10:26 UTC by richardhenryash

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)
https://tools.hmcts.net/jira/browse/COT-726

Notes:
* Fix for bug COT-726. Enables an array of strings of array to be passed in to 'find-person.service.ts' as 'assignedUser'.
* Any users already assigned are filtered out from the list.

2024-01-30 10:31 UTC, RiteshHMCTS approved these changes

2024-01-30 10:32 UTC, RiteshHMCTS requested changes
@richardhenryash you need to update version number in 2 package.json

2024-08-06 12:52 UTC, RiteshHMCTS approved these changes

2024-08-07 08:09 UTC, StoneBenHMCTS approved these changes

2024-09-03 11:49 UTC, merged