cot-874 - enabling the option to resubmit form after re-set to default
hmcts/rpx-xui-common-lib pull request #469
Opened 2024-10-15 07:45 UTC by anthonydummer

Notes:
* new variable resubmitOnCancel added giving the option to redefine the cancel button as a submit.  This is for the request to have the reset to default button in All Work to re-submit the form when selected and not require the user to then hit the apply button

2024-10-15 16:30 UTC, RiteshHMCTS approved these changes

2024-10-16 09:54 UTC, connorpgpmcelroy approved these changes
LGTM

2024-10-16 13:01 UTC, andywilkinshmcts requested changes
rename to "submitOnCancel|"

2024-10-16 14:07 UTC, anthonydummer commented on projects/exui-common-lib/src/lib/models/filter.model.ts
> +  resubmitOnCancel?: boolean;
Have changed name to submitOnCancel

2026-03-26 19:25 UTC, closed without merging